name: hello world print

on:
  pull_request:
    types: [opened]

jobs:
  trigger index.js:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Print hello world
        run: echo hello world!!!! from Ian cha
