name: hello world print

on:
  issues:
    types:
      - opened

jobs:
  hello_world_job: # Removed space and period
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "hello world!!!! from Ian cha"
  print_issue_title: # Removed space and period
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        env:
          # Store the title in an environment variable for safety
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "The issue title is: $ISSUE_TITLE"
          echo "Hello world!!!! from Ian cha"
